-- Migration: 0008_force_row_level_security.down.sql

ALTER TABLE branches NO FORCE ROW LEVEL SECURITY;
ALTER TABLE users NO FORCE ROW LEVEL SECURITY;
ALTER TABLE roles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE accounts NO FORCE ROW LEVEL SECURITY;
ALTER TABLE journal_entries NO FORCE ROW LEVEL SECURITY;
ALTER TABLE journal_lines NO FORCE ROW LEVEL SECURITY;
ALTER TABLE customers NO FORCE ROW LEVEL SECURITY;
ALTER TABLE suppliers NO FORCE ROW LEVEL SECURITY;
ALTER TABLE warehouses NO FORCE ROW LEVEL SECURITY;
ALTER TABLE stock_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE inventory_transactions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sales_invoices NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sales_invoice_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE purchase_invoices NO FORCE ROW LEVEL SECURITY;
ALTER TABLE purchase_invoice_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE cheques NO FORCE ROW LEVEL SECURITY;
ALTER TABLE customer_payments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE supplier_payments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE party_ledger_entries NO FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_logs NO FORCE ROW LEVEL SECURITY;

REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM erp_app_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM erp_app_role;

REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public FROM erp_app_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM erp_app_role;

DROP ROLE IF EXISTS erp_app_role;
